### ISSUE TITLE
import into cakephp

### ISSUE THREAD

**Issue by raheemrize** [wildbit/postmark-php#10]
Hi have installed this library through composer in a cakephp project. And it was installed under vendor directory. While i'm importing PostmarkClient.php into a controller, it is always throwing an error 'class PostmarkClient not found'.
Please help me.

**Comment by atheken** [comment]
Composer packages should be imported using a require_once declaration, as shown here:
http://support.postmarkapp.com/customer/portal/emails/new

You will need to include:

```php
require_once('./vendor/autoload.php');
use Postmark\PostmarkClient;
```

"./vendor" assumes you are running this script from the base directory of your project, but you can can adjust this path so that it is relative to the script you are running.

Please contact [Postmark Support](http://support.postmarkapp.com/) directly if you need more help
