### ISSUE TITLE
feature request: override email subject when using sendEmailWithTemplate()

### ISSUE THREAD

**Issue by sionirvine** [wildbit/postmark-php#15]
hi, really nice library by the way :+1: 
i think it's really convenient if user able to override email subject even when using a template,
but if the user doesn't want to change the default subject from the template then this function will use the default subject.
is this feature is possible to implement?

**Comment by atheken** [comment]
Hi @sionirvine,

Thanks for the feedback. Postmark Templates support Mustachio syntax within the Subject itself, a really simple way to accomplish this from the client is to set up your template with a conditional on a variable, such as this:

`{{^subject}}Default subject text{{/subject}}{{{subject}}}`

This will render "Default subject text" unless `subject` has a non-falsey value in your template model, in which case, the value of `subject` would be used. Also note that I am using THREE sets of `{ }` instead of two so that your subject does not get HTML-entity encoded.

(See this wiki article for more info on the Mustachio syntax: https://github.com/wildbit/mustachio/wiki)

Since what you're after is basically already supported, I'm going to close this issue. Please feel free to re-open if you have more questions or comments on this.
