### ISSUE TITLE
Instructions for testing

### ISSUE THREAD

**Issue by designermonkey** [wildbit/postmark-php#31]
Are there any instructions or default keys for actually testing this project? It would be useful to have the default set be provided in the repository.

**Comment by atheken** [comment]
Hi @designermonkey -- Here's some info about providing "default keys"; The short answer is that we won't publish them because they could be used for evil: https://github.com/wildbit/postmark-php/wiki/Running-Tests

However, if you want to help out on the project in large (or small) ways, please feel free to contact Postmark Support, and they'll connect us up via private email.
