### ISSUE TITLE
Error out of the box

### ISSUE THREAD

**Issue by Dottenpixel** [wildbit/postmark-php#4]
Any clue why I would be getting this error right out of the box?

I was trying to do the simple example posted on the [Postmark site](http://developer.postmarkapp.com/developer-official-libs.html#php). It seems there isn't anything in my code causing the error because when I load `PostMark/PostmarkClient.php`, the same error shows up:

![screen shot 2015-03-11 at 11 22 49 am](https://cloud.githubusercontent.com/assets/227507/6603875/e46de272-c7e1-11e4-9c96-5f6ce97acbe5.png)

**Comment by atheken** [comment]
Hi @Dottenpixel. Did you install Postmark-PHP using Composer? Or did you download download the package and unzip it in your web application?

**Comment by atheken** [comment]
In order to use Postmark-PHP, it must be installed via composer using the following command:

`composer require wildbit/postmark-php`

After doing this, there is typically a file in the project's root directory called `vendor/autoload.php`

In order to use the package, this will need to be required in the application's code before attempting to access namespaces in the Postmark-PHP package:

For example, let's assume there is in a file called `index.php` in the root of your application, you'd include this line:
`require_once './vendor/autoload.php';`

If the error you encountered happened even when installing from composer, please reopen this issue and we'll keep working with you on resolving it.
