### ISSUE TITLE
Making a GET request to /templates/validate (getting template aliased 'validate') doesn't work.

### ISSUE THREAD

**Issue by Lootfi** [wildbit/postmark-php#75]
First things first, If this is mentioned in the docs or it's just something wrong with my code then I apologize.

I'm not sure if it's just this library as I haven't tried making a curl request instead ..

Can someone please verify this?

Edit: I tried a request using curl and got the same error, so I guess it's not specific to this library.
```
{
  "ErrorCode": 1109,
  "Message": "No template data received."
}
```

**Comment by vladsandu** [comment]
@Lootfi sorry for the delay in getting to this issue. This is not related to Postmark-PHP but to the Postmark API.

We have an existing route pointing to `templates/validate`, used by the Template Validation endpoint, as presented in our [Templates API docs](https://postmarkapp.com/developer/api/templates-api#validate-template).

Because of that endpoint route conflict, unfortunately we do not support fetching a template via an alias named "validate". If you need to keep that exact alias name in place, you can alternatively use the associated `TemplateID` instead, e.g.: `/templates/123456`.

Sorry for the inconvenience! Looking back, this naming should probably have been reserved to avoid confusion.

Please let us know if you encounter any other issues.
