### ISSUE TITLE
[Question] With TLS changes in April, do I need to change anything?

### ISSUE THREAD

**Issue by mzzovko** [wildbit/postmark-php#78]
Hi,
I recently received this email about TLS changes, I'm using version 2.11 in an old project - do I need to change anything except update the package version so Postmark continues to work after April?

Link from email
https://postmarkapp.com/updates/upcoming-tls-configuration-changes-for-api-users-action-may-be-required

**Comment by briankerr** [comment]
Hi @mzzovko,

The package itself will continue to work without upgrading, though you will want to make sure your connection to Postmark is using TLSv1.1+.

The requirements to connect to Postmark after the TLS changes are:

- PHP version 5.5.19 or higher
- cURL version 7.34.0 or higher
- OpenSSL version 1.0.1 or higher

You can further test against our test API endpoint, this endpoint acts how our standard endpoint will work after the upgrade. You can do this by temporarily setting the BaseURL to point to the test endpoint, to validate your system works with these changes:

```
use Postmark\PostmarkClient;
use Postmark\PostmarkClientBase;

// Temporarily set the BaseURL globally to point to the test endpoint
PostmarkClientBase::$BASE_URL = "https://api-ssl-temp.postmarkapp.com";

$client = new PostmarkClient("<server token>");
```

Let me know if you have any questions on this!

**Comment by netcarver** [comment]
@briankerr Regarding the cURL requirement you mentioned, I have a machine running with version 7.29.0 (according to PHP Info) that does work with the new endpoint as shown in your code above. Is this expected?

**Comment by netcarver** [comment]
@briankerr Is there anything I can look for in the email headers to ensure that the received email was actually processed by the test endpoint? Might be useful for client assurance that their test sends are actually going through the intended endpoint.

**Comment by briankerr** [comment]
@netcarver Hi Steve 👋 I'm checking with some colleagues on your questions (I want to make sure I have an accurate answer). After speaking with them, I'll follow-up with you (most likely, tomorrow, the 9th).

**Comment by netcarver** [comment]
@briankerr Hi Brian, thanks for the follow-up. I checked in with one of your colleagues on the support team to see if our test emails were using TLS1.2 and it appears they were - however, we definitely are not meeting your quoted minimum install version for cURL.

**Comment by briankerr** [comment]
@netcarver Hi Steve! Thank you for your patience. 

cURL version 7.34.0 is the first version of cURL to default to TLSv1.2. So it is possible to use an older version of cURL, though those connections default to an older version of TLS "out of the box" if you will. It looks like you're Red Hat and [they've included a default for a higher default version of TLS as part of the OS for 7.29](https://git.centos.org/rpms/curl/blob/f0f8d7eb232b023d7cb9dfb16851b7e02d822922/f/SPECS/curl.spec#_652). Since we've verified your connection is TLSv1.2, you're good here.

When it comes to finding the hostname endpoint you're using, since this is a rare type of cutover, we don't give visibility into this within our UI since we normally only have `api.postmarkapp.com`. If you were looking for additional assurances, you could use our [custom metadata](https://postmarkapp.com/support/article/1125-custom-metadata-faq) feature to pass which endpoint your API call is making to see that in our UI. Though I don't think this is necessary for your situation.

**Comment by mzzovko** [comment]
Thanks both @briankerr & @netcarver  - I've tested it and it works 👍
