### ISSUE TITLE
Requirement for GuzzleHttp

### ISSUE THREAD

**Issue by jxmallett** [wildbit/postmark-php#8]
`PostmarkClientBase` currently requires GuzzleHttp. It looks like this dependency could be easily removed by using curl. I do this in my project at the moment by extending `PostmarkClient` and overriding `processRestRequest()` with a function I've written myself. I haven't noticed any issues, but I only send email.

Is there some larger reason to use Guzzle?

**Comment by atheken** [comment]
Hi Julian,

I tend to fall on the side of "minimal dependencies", so I'm right there with you on removing libraries that don't add much "flavor."

Although curl is usually available, we wanted to make sure that users had the best (and most predictable) experience when installing the library. Using Guzzle, which can fallback to other methods on systems that don't have curl enabled, supported that goal. We expect that since Guzzle is already fairly common (6-9 million installs according to packagist -- depending on how you count), this added requirement for a well-supported HTTP client is not particularly onerous.

If you have a branch with your http handling enabled, I'd be happy to look it over, but we'll probably want to keep Guzzle as it's pretty well tested, and handles a few other issues pretty well for the library.

We very much appreciate the feedback!

**Comment by jxmallett** [comment]
Thanks for the info @atheken. Sounds like a good reason to keep Guzzle in there. I'll leave things be :)
